# Generated by Django 5.0.6 on 2024-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('width', models.IntegerField()),
                ('lenght', models.IntegerField()),
                ('height', models.IntegerField()),
                ('price', models.IntegerField()),
                ('paid', models.BooleanField()),
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
